### ISSUE TITLE
Latest release 3.5.0-py_1000 is broken

### ISSUE THREAD

**Issue by gatesn** [conda-forge/configparser-feedstock#16]
Caused by https://github.com/conda-forge/configparser-feedstock/pull/14/files

Results in errors like this:

```
  File "/.../lib/python2.7/site-packages/pylint/config.py", line 49, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by ocefpaf** [comment]
Probably fixed in #17 

@gatesn can you please check it again when the new packages are only? I just merged it and they should be up in the channel in a few minutes.
